language: ruby
rvm:
- '2.5'
- '2.6'
- '2.7'

cache:
  bundler: true
env:
  global:
    - GENGO_PUBKEY='pubkeyfortests' GENGO_PRIVKEY='privatekeyfortestuserthatcontainsonlyletters'
before_install:
- gem update bundler
