language: ruby
rvm:
- 2.0.0
- '2.1'
- '2.2'
- '2.3'

cache:
  bundler: true
env:
  global:
    - GENGO_PUBKEY='pubkeyfortests' GENGO_PRIVKEY='privatekeyfortestuserthatcontainsonlyletters'
before_install:
- gem update bundler
